site_name: "Grupo 5 - Tesouro Direto"
repo_url: https://github.com/Requisitos-de-Software/2024.2-Grupo05
      
extra_css:
  - stylesheets/style.css

nav:
  - Home: index.md
  - Atas:
    - Ata 1: Atas/ata01.md
    - Ata 2: Atas/ata02.md
    - Ata 3: Atas/ata03.md

  - Apresentações:
    - Apresentação 1: Apresentacoes/apresentacao01.md
    - Apresentação 2: Apresentacoes/apresentacao02.md
    - Apresentação 3: Apresentacoes/apresentacao03.md
    - Apresentação 4: Apresentacoes/apresentacao04.md
    - Apresentação 5: Apresentacoes/apresentacao07.md
    - Apresentação 6: Apresentacoes/apresentacao06.md
    

  - Planejamento do projeto:
    - Heatmap: Planejamento-do-projeto/heatmap.md
    - Lista de apps avaliados: Planejamento-do-projeto/lista-apps-avaliados.md
    - App Escolhido:
      - App Escolhido: Planejamento-do-projeto/app-escolhido.md
      - Rich Picture: Planejamento-do-projeto/rich-picture.md
    - Cronogramas:
      - Cronograma Planejado: Planejamento-do-projeto/cronograma-planejado.md
      - Cronograma Executado: Planejamento-do-projeto/cronograma-executado.md
    - Ferramentas: Planejamento-do-projeto/ferramentas.md

  - Elicitação de Requisitos:
    - Definição do Perfil de Usuário:
      - Perfil de Usuário: elicitacao/grupo5/definicao-perfil_de_usuario/perfil-usuario.md
      - Questionário: elicitacao/grupo5/definicao-perfil_de_usuario/questionario.md
    - Personas: elicitacao/grupo5/personas.md
    - Técnicas:
      - Introspecção: elicitacao/grupo5/introspeccao.md
      - Brainstorm: elicitacao/grupo5/brainstorm.md
      - Grupo de foco: elicitacao/grupo5/grupo-de-foco.md
      - Glossário: elicitacao/grupo5/glossario.md
    - Priorização:
      - Cronograma: elicitacao/grupo5/priorizacao/cronograma.md 
      - 100$: elicitacao/grupo5/priorizacao/100$.md
      - In or Out: elicitacao/grupo5/priorizacao/inorout.md
      - Three Level Scale: elicitacao/grupo5/priorizacao/threelevelscale.md
    - Requisitos Elicitados: elicitacao/grupo5/requisitos.md

  - Modelagem:
    - Léxicos: modelagem-pt1/lexicos.md
    - Cenários: modelagem-pt1/cenarios.md
    - Casos de Uso: modelagem-pt1/casos-de-uso.md
    - Validação dos Casos de Uso: modelagem-pt1/validacaoCasodeUso.md
    - Especificação Suplementar: modelagem-pt1/especificacao-suplementar.md
    - Ágil:
      - Backlog: modelagem-pt2/backlog.md
      - NFR Framework: modelagem-pt2/nfr_framework.md
      - Histórias de Usuário: modelagem-pt2/userstories.md
      
  - Verificação:
    - Panorama geral: verificacao/lv-geral.md
    - Grupo 5:
      - Entrega 1:
        - Planejamento da verificação: verificacao/grupo5/entrega1/planej2-e1.md
        - Relatório de verificação: 
          - Heatmap: verificacao/grupo5/entrega1/r-heatmap.md
          - Lista de apps avaliados: verificacao/grupo5/entrega1/r-lista-app-avaliados.md
          - App Escolhido: verificacao/grupo5/entrega1/r-app-escolhido.md
          - Rich Picture: verificacao/grupo5/entrega1/r-rich-picture.md
          - Cronograma: verificacao/grupo5/entrega1/r-cronograma.md
          - Ferramentas: verificacao/grupo5/entrega1/r-ferramentas.md
        - Verificação do Monitor: verificacao/grupo5/entrega1/verificacao-monitor.md
      - Entrega 2:
        - Planejamento da verificação: verificacao/grupo5/entrega2/planej2-e2.md
        - Relatório de verificação: 
          - Perfil de Usuário: verificacao/grupo5/entrega2/r-perfil-de-usuario.md
          - Questionário: verificacao/grupo5/entrega2/r-questionario.md
          - Personas: verificacao/grupo5/entrega2/r-personas.md
          - Introspecção: verificacao/grupo5/entrega2/r-introspeccao.md
          - Brainstorm: verificacao/grupo5/entrega2/r-brainstorm.md
          - Grupo de foco: verificacao/grupo5/entrega2/r-grupo-foco.md
          - Glossário: verificacao/grupo5/entrega2/r-glossario.md
          - Priorização 100$: verificacao/grupo5/entrega2/r-100$.md
          - Priorização In or Out: verificacao/grupo5/entrega2/r-in-or-out.md
          - Priorização Three Level Scale: verificacao/grupo5/entrega2/r-three-level-scale.md
      - Entrega 3:
        - Planejamento da verificação: verificacao/grupo5/entrega3/planej2-e3.md
        - Relatório de verificação:
          - Léxicos: verificacao/grupo5/entrega3/r-lexicos.md
          - Cenários: verificacao/grupo5/entrega3/r-cenarios.md
          - Casos de Uso: verificacao/grupo5/entrega3/r-casos-uso.md
          - Validação dos Casos de Uso: verificacao/grupo5/entrega3/r-valid-caso-uso.md
          - Especificação Suplementar: verificacao/grupo5/entrega3/r-especificacao.md
      - Entrega 4:
        - Planejamento da verificação: verificacao/grupo5/entrega4/planej2-e4.md
        - Relatório de verificação: 
          - Backlog: verificacao/grupo5/entrega4/r-backlog.md
          - NFR Framework: verificacao/grupo5/entrega4/r-nfr.md
          - História de Usuário: verificacao/grupo5/entrega4/r-us.md
      - Entrega 6:
        - Planejamento da verificação: verificacao/grupo5/entrega6/planej2-e6.md
        - Relatório de verificação: 
          - Matriz de Rastreabilidade: verificacao/grupo5/entrega6/r-matriz.md
          - Backward-From: verificacao/grupo5/entrega6/r-backward.md
          - Forward-From: verificacao/grupo5/entrega6/r-forward.md
    - Grupo +1 (6):
      - Planejamento Geral: verificacao/grupo6/planej-geral.md
      - Entrega 1:
        - Planejamento da verificação: verificacao/grupo6/entrega1/planej2-e1.md
        - Relatório de verificação: 
          - Heatmap: verificacao/grupo6/entrega1/r-heatmap.md
          - Lista de apps avaliados: verificacao/grupo6/entrega1/r-lista-app-avaliados.md
          - App Escolhido: verificacao/grupo6/entrega1/r-app-escolhido.md
          - Rich Picture: verificacao/grupo6/entrega1/r-rich-picture.md
          - Cronograma: verificacao/grupo6/entrega1/r-cronograma.md
          - Ferramentas: verificacao/grupo6/entrega1/r-ferramentas.md
      - Entrega 2:
        - Planejamento da verificação: verificacao/grupo6/entrega2/planej2-e2.md
        - Relatório de verificação: 
          - Perfil de Usuário: verificacao/grupo6/entrega2/r-perfil-de-usuario.md
          - Questionário: verificacao/grupo6/entrega2/r-questionario.md
          - Personas: verificacao/grupo6/entrega2/r-personas.md
          - Introspecção: verificacao/grupo6/entrega2/r-introspeccao.md
          - Glossário: verificacao/grupo6/entrega2/r-glossario.md
          - Priorização 100$: verificacao/grupo6/entrega2/r-100$.md
          - Priorização Three Level Scale: verificacao/grupo6/entrega2/r-three-level-scale.md
      - Entrega 3:
        - Planejamento da verificação: verificacao/grupo6/entrega3/planej2-e3.md
        - Relatório de verificação:
          - Léxicos: verificacao/grupo6/entrega3/r-lexicos.md
          - Cenários: verificacao/grupo6/entrega3/r-cenarios.md
          - Casos de Uso: verificacao/grupo6/entrega3/r-casos-uso.md
          - Validação dos Casos de Uso: verificacao/grupo6/entrega3/r-valid-caso-uso.md
          - Especificação Suplementar: verificacao/grupo6/entrega3/r-especificacao.md
      - Entrega 4:
        - Planejamento da verificação: verificacao/grupo6/entrega4/planej2-e4.md
        - Relatório de verificação: 
          - Backlog: verificacao/grupo6/entrega4/r-backlog.md
          - NFR Framework: verificacao/grupo6/entrega4/r-nfr.md
          - Histórias de Usuário: verificacao/grupo6/entrega4/r-us.md
      - Entrega 6:
        - Planejamento da verificação: verificacao/grupo6/entrega6/planej2-e6.md
        - Relatório de verificação: 
          - Backward: verificacao/grupo6/entrega6/r-backward.md
          - Forward: verificacao/grupo6/entrega6/r-forward.md
          - Matriz de Rastreabilidade: verificacao/grupo6/entrega6/r-matriz.md
  - Validação:
    - Protótipo de Alta Fidelidade: validacao/modelo.md
    - Comprovação Informal: validacao/comprovacao-informal.md
  - Pós Rastreabilidade:
    - Matriz de Rastreabilidade: pos-rastreabilidade/matriz-rastreabilidade.md 
    - Backward-From:  pos-rastreabilidade/backward-from.md
    - Forward-From:  pos-rastreabilidade/forward-from.md
  - Entrega Final: 
    - Execução do Projeto: final/execucao.md
    - Aplicativo Selecionado: final/aplicativoSelecionado.md
    - Planejamento dos Recursos e Entregas: final/recursosEntregas.md
    - Técnicas Utilizadas: final/tecnicas-utilizadas.md
    - Ferramentas Utilizadas: final/ferramentas-utilizadas.md
    - Artefatos Criados: final/artefatos-criados.md

theme:
  logo: assets/header-logo-tesourodireto.png
  name: material
  font:
    text: IBM Plex Serif
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.copy
  palette:
    - scheme: light
      primary: custom
      toggle:
        icon: material/weather-night
        name: Trocar para modo escuro

    - scheme: slate
      primary: custom
      toggle:
        icon: material/weather-sunny
        name: Trocar para modo claro
  icon:
    repo: fontawesome/brands/github


markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true